### ISSUE TITLE
Potential problem with mysql PDO constructor in php7

### ISSUE THREAD

**Issue by greg-1-anderson** [lcache/wp-lcache#132] opened 2017-05-10 18:51 UTC
There was a [problem reported on a php 7 site using this module](https://getpantheon.atlassian.net/browse/BUGS-1259?focusedCommentId=47131&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-47131) related to the [port specification for the PDO constructor](https://github.com/lcache/wp-lcache/blob/3ad270ce18cbb235e7c8125d3fa8ec5b4c5215bc/object-cache.php#L1190).

The [Mysql PDO constructor documentation](http://php.net/manual/en/ref.pdo-mysql.php) doesn't appear to say anything about requirements changes for php 7.

Related to https://github.com/pantheon-cookbooks/drush/pull/32

**Comment by danielbachhuber** [comment] 2017-05-10 19:08
> The Mysql PDO constructor documentation doesn't appear to say anything about requirements changes for php 7.

Meaning, the syntax changed?

**Comment by greg-1-anderson** [comment] 2017-05-10 19:25
In the `mysqli_connect` API function, in PHP 7, the port can no longer be specified as part of the host string (first parameter); it must be provided in the `port` parameter. So, the syntax for this function did not change, but the behavior did change insofar as the interpretation of the parameters is now stricter than it was before.

I suspect the same thing happened with the Mysql PDO constructor, but the documentation is not clear on how the port is supposed to be specified. In the failing code, it is embedded in the first parameter, similar to how it used to be done with `mysqli_connect`.

**Comment by greg-1-anderson** [comment] 2017-05-10 19:26
See also: https://getpantheon.atlassian.net/browse/BUGS-1266

**Comment by danielbachhuber** [comment] 2017-05-10 20:00
@greg-1-anderson What do you think is the severity of this issue? Fix in the next 24 hours or fix in the next week?

cc @fjarrett

**Comment by frankiejarrett** [comment] 2017-05-10 20:10
@danielbachhuber I can't open any of the related bug reports links cited above, but it looks like the DSN we pass to the PDO constructor is formatted just fine.

https://github.com/lcache/wp-lcache/blob/3ad270ce18cbb235e7c8125d3fa8ec5b4c5215bc/object-cache.php#L1082

**Comment by greg-1-anderson** [comment] 2017-05-10 20:38
```
Fatal error: Uncaught PDOException: SQLSTATE[HY000] [2002] Failed to parse address "10.223.224.69:22394:22394" in /srv/bindings/ef256c833df94d0b8b7cd9a10ba6005f/code/wp-content/plugins/wp-lcache/object-cache.php:1159 Stack trace: #0 
/srv/bindings/ef256c833df94d0b8b7cd9a10ba6005f/code/wp-content/plugins/wp-lcache/object-cache.php(1159): PDO->__construct('mysql:host=10.2...', 'pantheon', 'dc9b111e87cc492...', Array) #1 /srv/bindings/ef256c833df94d0b8b7cd9a10ba6005f/code/wp-content/plugins/wp-lcache/object-cache.php(165): WP_Object_Cache->__construct() #2 /srv/bindings/ef256c833df94d0b8b7cd9a10ba6005f/code/wp-includes/load.php(514): wp_cache_init() #3 /srv/bindings/ef256c833df94d0b8b7cd9a10ba6005f/code/wp-settings.php(114): wp_start_object_cache() #4 /srv/bindings/ef256c833df94d0b8b7cd9a10ba6005f/code/wp-config.php(208): require_once('/srv/bindings/e...') #5 /srv/bindings/ef256c833df94d0b8b7cd9a10ba6005f/code/wp-load.php(37): require_once('/srv/bindings/e...') #6 /srv/bindings/ef256c833df94d0b8b7cd9a10ba6005f/code/wp-blog-he in /srv/bindings/ef256c833df94d0b8b7cd9a10ba6005f/code/wp-content/plugins/wp-lcache/object-cache.php on line 1159
```

Encountered on PHP 7.0.18. Behavior may have recently changed in this release. Not sure about severity. cc: @davidstrauss

**Comment by danielbachhuber** [comment] 2017-05-10 22:41
> Encountered on PHP 7.0.18. Behavior may have recently changed in this release.

@greg-1-anderson "this release", meaning PHP 7.0.18?

Related https://github.com/lcache/wp-lcache/issues/117

**Comment by greg-1-anderson** [comment] 2017-05-10 22:58
Yes, or perhaps in 7.0.17. Unconfirmed.

**Comment by joshkoenig** [comment] 2017-05-23 17:00
This same bug is popping up in other contexts as well. @danielbachhuber can you help us understand what's going on here? If we need to fix our code we should, or should we improve/fix some documentation?

**Comment by danielbachhuber** [comment] 2017-05-23 18:25
> @danielbachhuber can you help us understand what's going on here?

Yes, I'll look.

**Comment by danielbachhuber** [comment] 2017-05-24 13:36
@greg-1-anderson I tried reproducing the issue this morning and wasn't able to. Can you provide some guidance on how to reproduce?

Here's what I did:

* Created a new environment: http://dev-wp-lcache-test-may-2017.pantheonsite.io/
* Committed a `pantheon.yml` file to set `php_version: 7.0`
* Verified PHP version 7.0.18: http://dev-wp-lcache-test-may-2017.pantheonsite.io/phpinfo.php
* Installed WP LCache 0.5.2 from WordPress.org
* Enabled WP LCache with `terminus wp wp-lcache-test-may-2017.dev -- lcache enable`

WP LCache is running in WordPress without errors:

![image](https://cloud.githubusercontent.com/assets/36432/26405692/ed2dd582-404a-11e7-94b9-3babeefeade8.png)

In the error message mentioned in https://github.com/lcache/wp-lcache/issues/132#issuecomment-300605445

> ```
> Fatal error: Uncaught PDOException: SQLSTATE[HY000] [2002] Failed to parse address "10.223.224.69:22394:22394" in /srv/bindings/ef256c833df94d0b8b7cd9a10ba6005f/code/wp-content/plugins/wp-lcache/object-cache.php:1159 Stack trace: #0 
> /srv/bindings/ef256c833df94d0b8b7cd9a10ba6005f/code/wp-content/plugins/wp-lcache/object-cache.php(1159): PDO->__construct('mysql:host=10.2...', 'pantheon', 'dc9b111e87cc492...', Array) #1 /srv/bindings/ef256c833df94d0b8b7cd9a10ba6005f/code/wp-content/plugins/wp-lcache/object-cache.php(165): WP_Object_Cache->__construct() #2 /srv/bindings/ef256c833df94d0b8b7cd9a10ba6005f/code/wp-includes/load.php(514): wp_cache_init() #3 /srv/bindings/ef256c833df94d0b8b7cd9a10ba6005f/code/wp-settings.php(114): wp_start_object_cache() #4 /srv/bindings/ef256c833df94d0b8b7cd9a10ba6005f/code/wp-config.php(208): require_once('/srv/bindings/e...') #5 /srv/bindings/ef256c833df94d0b8b7cd9a10ba6005f/code/wp-load.php(37): require_once('/srv/bindings/e...') #6 /srv/bindings/ef256c833df94d0b8b7cd9a10ba6005f/code/wp-blog-he in /srv/bindings/ef256c833df94d0b8b7cd9a10ba6005f/code/wp-content/plugins/wp-lcache/object-cache.php on line 1159
> ```

I notice the `mysql:host` is set to `10.223.224.69:22394:22394` (note port is duplicated).

Is there something different about the environment that causes the port to be duplicated in the host?

**Comment by frankiejarrett** [comment] 2017-05-24 14:07
@danielbachhuber FWIW I tried PHP 7.0.19 and also was unable to reproduce.

**Comment by greg-1-anderson** [comment] 2017-05-24 14:12
I never reproduced this problem myself -- I was passing along the report. The issue I linked to was a different problem, the mysql_connect issue in `btool drush` that has already been fixed. I can't find an issue for the PDO constructor. As I mentioned above, the documentation does not mention anything changing in this method. @joshkoenig do you have any information on the other contexts where this bug is being encountered?

I'll check with support and see if someone can point us to the correct original report.

**Comment by wkhayrattee** [comment] 2017-06-04 19:15
Hi everyone. What's the status with this issue. Has it been reproduced? I believe if it has occurred once, we should be understanding the how to prevent any future surprises. thanks

**Comment by greg-1-anderson** [comment] 2017-06-04 19:21
At this point, I believe that the problem with the PDO constructor was a false report / misunderstanding. If you need more information about the mysql_connect issue, please let me know, and I can fill you in. However, I do not believe that problem ever affected this component.

**Comment by wkhayrattee** [comment] 2017-06-04 19:46
Hi @greg-1-anderson thanks for the reply, appreciate.
Yes, please if you could give me more info on the mysql_connect issue, would be great for my own dev team if we encounter something similar. My email is: w@7php.com 
Cheers

**Comment by greg-1-anderson** [comment] 2017-06-04 20:36
The known issue relates to [mysqli::_construct](http://php.net/manual/en/mysqli.construct.php) and [mysqli_connect](http://php.net/manual/en/function.mysqli-connect.php). These are the newer versions of [mysql_connect](http://php.net/manual/en/function.mysql-connect.php).

In newer versions of php 7, the optional *port* parameter of these new functions must be used if a non-standard port is desired. Previously, mysqli_connect would allow a mysql_connect-style server string, with the port specified as part of host string. Fixing these bugs a simple matter of removing the :port from the server string and passing it as the port parameter.

**Comment by frankiejarrett** [comment] 2017-06-04 21:08
Proper support for splitting the port/hostname from `DB_NAME` was done in #115.

**Comment by greg-1-anderson** [comment] 2017-06-05 01:30
OK, great; maybe the original report was from a version prior to that fix, then. Seems like everything is okay here now.

**Closed as completed** 2017-11-09 13:00 UTC
Labels: bug
